spring.application.name=fitness-tracker-api

spring.datasource.url=jdbc:postgresql://localhost:5432/fitness
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

jwt.secret.key=bXktc3VwZXItc2VjdXJlLWFuZC1sb25nLWVub3VnaC1zZWNyZXQta2V5LWZvci1qd3QtMjU2LWJpdHM=
jwt.expiration.ms=86400000
jwt.refresh.expiration.ms=604800000

s3.endpoint=http://localhost:9000
s3.access-key=minioadmin
s3.secret-key=minioadminpassword
s3.bucket-name=progress-photos